// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdverotzpodiutorebie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkdmVyb3R6cG9kaXV0b3JlYmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDY5MzcsImV4cCI6MjA3NDQ4MjkzN30.5vGq2NQEQcRoS-Se2XtT8LYuh1sUtN87NKvRy5D3f0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});